from collections.abc import Iterable
from typing import Any, Protocol


class RawJsonProtocol(Protocol):
    """Protocol for raw json data access.

    This class defines the methods that must be implemented to access
    raw JSON data as an iterable of dictionaries for various SDE JSONL files.

    Each method corresponds to a specific SDE file and returns an
    iterable of dictionaries representing the JSON objects in that file.

    This will be a building block for later more specific data access protocols.

    The method names are derived from the SDE file names by converting them
    to snake_case and removing the ".jsonl" extension. Except that `types.jsonl`
    becomes `eve_types()` to avoid conflict and confusion with the built-in `type` function.

    Most functions return an Iterable of dictionaries, except for the following:
    - sde_info(): Returns a dictionary with string or integer values representing SDE metadata.



    """

    def agents_in_space(self) -> Iterable[dict[str, Any]]: ...
    def agent_types(self) -> Iterable[dict[str, Any]]: ...
    def ancestries(self) -> Iterable[dict[str, Any]]: ...
    def bloodlines(self) -> Iterable[dict[str, Any]]: ...
    def blueprints(self) -> Iterable[dict[str, Any]]: ...
    def categories(self) -> Iterable[dict[str, Any]]: ...
    def certificates(self) -> Iterable[dict[str, Any]]: ...
    def character_attributes(self) -> Iterable[dict[str, Any]]: ...
    def compressible_types(self) -> Iterable[dict[str, Any]]: ...
    def contraband_types(self) -> Iterable[dict[str, Any]]: ...
    def control_tower_resources(self) -> Iterable[dict[str, Any]]: ...
    def corporation_activities(self) -> Iterable[dict[str, Any]]: ...
    def debuff_collections(self) -> Iterable[dict[str, Any]]: ...
    def dogma_attribute_categories(self) -> Iterable[dict[str, Any]]: ...
    def dogma_attributes(self) -> Iterable[dict[str, Any]]: ...
    def dogma_effects(self) -> Iterable[dict[str, Any]]: ...
    def dogma_units(self) -> Iterable[dict[str, Any]]: ...
    def dynamic_item_attributes(self) -> Iterable[dict[str, Any]]: ...
    def factions(self) -> Iterable[dict[str, Any]]: ...
    def freelance_job_schemas(self) -> dict[str, Any]: ...
    def graphics(self) -> Iterable[dict[str, Any]]: ...
    def groups(self) -> Iterable[dict[str, Any]]: ...
    def icons(self) -> Iterable[dict[str, Any]]: ...
    def landmarks(self) -> Iterable[dict[str, Any]]: ...
    def map_asteroid_belts(self) -> Iterable[dict[str, Any]]: ...
    def map_constellations(self) -> Iterable[dict[str, Any]]: ...
    def map_moons(self) -> Iterable[dict[str, Any]]: ...
    def map_planets(self) -> Iterable[dict[str, Any]]: ...
    def map_regions(self) -> Iterable[dict[str, Any]]: ...
    def map_solar_systems(self) -> Iterable[dict[str, Any]]: ...
    def map_stargates(self) -> Iterable[dict[str, Any]]: ...
    def map_stars(self) -> Iterable[dict[str, Any]]: ...
    def market_groups(self) -> Iterable[dict[str, Any]]: ...
    def masteries(self) -> Iterable[dict[str, Any]]: ...
    def meta_groups(self) -> Iterable[dict[str, Any]]: ...
    def npc_characters(self) -> Iterable[dict[str, Any]]: ...
    def npc_corporation_divisions(self) -> Iterable[dict[str, Any]]: ...
    def npc_corporations(self) -> Iterable[dict[str, Any]]: ...
    def npc_stations(self) -> Iterable[dict[str, Any]]: ...
    def planet_resources(self) -> Iterable[dict[str, Any]]: ...
    def planet_schematics(self) -> Iterable[dict[str, Any]]: ...
    def races(self) -> Iterable[dict[str, Any]]: ...
    def sde_info(self) -> dict[str, Any]: ...
    def skin_licenses(self) -> Iterable[dict[str, Any]]: ...
    def skin_materials(self) -> Iterable[dict[str, Any]]: ...
    def skins(self) -> Iterable[dict[str, Any]]: ...
    def sovereignty_upgrades(self) -> Iterable[dict[str, Any]]: ...
    def station_operations(self) -> Iterable[dict[str, Any]]: ...
    def station_services(self) -> Iterable[dict[str, Any]]: ...
    def translation_languages(self) -> Iterable[dict[str, Any]]: ...
    def type_bonus(self) -> Iterable[dict[str, Any]]: ...
    def type_dogma(self) -> Iterable[dict[str, Any]]: ...
    def type_materials(self) -> Iterable[dict[str, Any]]: ...
    def eve_types(self) -> Iterable[dict[str, Any]]: ...
