"""The type signatures of SDE JSONL files for build 3201939."""

from typing import Any

sig: dict[str, Any] = {
    "_sde.jsonl": {
        "dict_count": 1,
        "key_info": {
            "_key": {"str": 1},
            "buildNumber": {"int": 1},
            "releaseDate": {"str": 1},
        },
        "source_info": "_sde.jsonl (build 3201939)",
    },
    "agentTypes.jsonl": {
        "dict_count": 13,
        "key_info": {"_key": {"int": 13}, "name": {"str": 13}},
        "source_info": "agentTypes.jsonl (build 3201939)",
    },
    "agentsInSpace.jsonl": {
        "dict_count": 360,
        "key_info": {
            "_key": {"int": 360},
            "dungeonID": {"int": 360},
            "solarSystemID": {"int": 360},
            "spawnPointID": {"int": 360},
            "typeID": {"int": 360},
        },
        "source_info": "agentsInSpace.jsonl (build 3201939)",
    },
    "ancestries.jsonl": {
        "dict_count": 43,
        "key_info": {
            "_key": {"int": 43},
            "bloodlineID": {"int": 43},
            "charisma": {"int": 43},
            "description": {"dict": 43},
            "description.de": {"str": 43},
            "description.en": {"str": 43},
            "description.es": {"str": 43},
            "description.fr": {"str": 43},
            "description.ja": {"str": 43},
            "description.ko": {"str": 43},
            "description.ru": {"str": 43},
            "description.zh": {"str": 43},
            "iconID": {"int": 35},
            "intelligence": {"int": 43},
            "memory": {"int": 43},
            "name": {"dict": 43},
            "name.de": {"str": 43},
            "name.en": {"str": 43},
            "name.es": {"str": 43},
            "name.fr": {"str": 43},
            "name.ja": {"str": 43},
            "name.ko": {"str": 43},
            "name.ru": {"str": 43},
            "name.zh": {"str": 43},
            "perception": {"int": 43},
            "shortDescription": {"str": 42},
            "willpower": {"int": 43},
        },
        "source_info": "ancestries.jsonl (build 3201939)",
    },
    "bloodlines.jsonl": {
        "dict_count": 18,
        "key_info": {
            "_key": {"int": 18},
            "charisma": {"int": 18},
            "corporationID": {"int": 18},
            "description": {"dict": 18},
            "description.de": {"str": 18},
            "description.en": {"str": 18},
            "description.es": {"str": 18},
            "description.fr": {"str": 18},
            "description.ja": {"str": 18},
            "description.ko": {"str": 18},
            "description.ru": {"str": 18},
            "description.zh": {"str": 18},
            "iconID": {"int": 15},
            "intelligence": {"int": 18},
            "memory": {"int": 18},
            "name": {"dict": 18},
            "name.de": {"str": 18},
            "name.en": {"str": 18},
            "name.es": {"str": 18},
            "name.fr": {"str": 18},
            "name.ja": {"str": 18},
            "name.ko": {"str": 18},
            "name.ru": {"str": 18},
            "name.zh": {"str": 18},
            "perception": {"int": 18},
            "raceID": {"int": 18},
            "willpower": {"int": 18},
        },
        "source_info": "bloodlines.jsonl (build 3201939)",
    },
    "blueprints.jsonl": {
        "dict_count": 5059,
        "key_info": {
            "_key": {"int": 5059},
            "activities": {"dict": 5059},
            "activities.copying": {"dict": 4338},
            "activities.copying.materials": {"dict": 1820, "list": 1008},
            "activities.copying.materials.quantity": {"int": 1820},
            "activities.copying.materials.typeID": {"int": 1820},
            "activities.copying.skills": {"dict": 2139, "list": 1021},
            "activities.copying.skills.level": {"int": 2139},
            "activities.copying.skills.typeID": {"int": 2139},
            "activities.copying.time": {"int": 4338},
            "activities.invention": {"dict": 1110},
            "activities.invention.materials": {"dict": 2218, "list": 1109},
            "activities.invention.materials.quantity": {"int": 2218},
            "activities.invention.materials.typeID": {"int": 2218},
            "activities.invention.products": {"dict": 1354, "list": 1106},
            "activities.invention.products.probability": {"float": 1346},
            "activities.invention.products.quantity": {"int": 1354},
            "activities.invention.products.typeID": {"int": 1354},
            "activities.invention.skills": {"dict": 3415, "list": 1109},
            "activities.invention.skills.level": {"int": 3415},
            "activities.invention.skills.typeID": {"int": 3415},
            "activities.invention.time": {"int": 1110},
            "activities.manufacturing": {"dict": 4848},
            "activities.manufacturing.materials": {"dict": 26913, "list": 4831},
            "activities.manufacturing.materials.quantity": {"int": 26913},
            "activities.manufacturing.materials.typeID": {"int": 26913},
            "activities.manufacturing.products": {"dict": 4825, "list": 4825},
            "activities.manufacturing.products.quantity": {"int": 4825},
            "activities.manufacturing.products.typeID": {"int": 4825},
            "activities.manufacturing.skills": {"dict": 9143, "list": 4711},
            "activities.manufacturing.skills.level": {"int": 9143},
            "activities.manufacturing.skills.typeID": {"int": 9143},
            "activities.manufacturing.time": {"int": 4848},
            "activities.reaction": {"dict": 120},
            "activities.reaction.materials": {"dict": 400, "list": 120},
            "activities.reaction.materials.quantity": {"int": 400},
            "activities.reaction.materials.typeID": {"int": 400},
            "activities.reaction.products": {"dict": 120, "list": 120},
            "activities.reaction.products.quantity": {"int": 120},
            "activities.reaction.products.typeID": {"int": 120},
            "activities.reaction.skills": {"dict": 120, "list": 120},
            "activities.reaction.skills.level": {"int": 120},
            "activities.reaction.skills.typeID": {"int": 120},
            "activities.reaction.time": {"int": 120},
            "activities.research_material": {"dict": 4338},
            "activities.research_material.materials": {"dict": 2579, "list": 859},
            "activities.research_material.materials.quantity": {"int": 2579},
            "activities.research_material.materials.typeID": {"int": 2579},
            "activities.research_material.skills": {"dict": 3809, "list": 1483},
            "activities.research_material.skills.level": {"int": 3809},
            "activities.research_material.skills.typeID": {"int": 3809},
            "activities.research_material.time": {"int": 4338},
            "activities.research_time": {"dict": 4338},
            "activities.research_time.materials": {"dict": 2404, "list": 814},
            "activities.research_time.materials.quantity": {"int": 2404},
            "activities.research_time.materials.typeID": {"int": 2404},
            "activities.research_time.skills": {"dict": 3696, "list": 1466},
            "activities.research_time.skills.level": {"int": 3696},
            "activities.research_time.skills.typeID": {"int": 3696},
            "activities.research_time.time": {"int": 4338},
            "blueprintTypeID": {"int": 5059},
            "maxProductionLimit": {"int": 5059},
        },
        "source_info": "blueprints.jsonl (build 3201939)",
    },
    "categories.jsonl": {
        "dict_count": 48,
        "key_info": {
            "_key": {"int": 48},
            "iconID": {"int": 13},
            "name": {"dict": 48},
            "name.de": {"str": 48},
            "name.en": {"str": 48},
            "name.es": {"str": 48},
            "name.fr": {"str": 48},
            "name.ja": {"str": 48},
            "name.ko": {"str": 48},
            "name.ru": {"str": 48},
            "name.zh": {"str": 48},
            "published": {"bool": 48},
        },
        "source_info": "categories.jsonl (build 3201939)",
    },
    "certificates.jsonl": {
        "dict_count": 136,
        "key_info": {
            "_key": {"int": 136},
            "description": {"dict": 136},
            "description.de": {"str": 136},
            "description.en": {"str": 136},
            "description.es": {"str": 136},
            "description.fr": {"str": 136},
            "description.ja": {"str": 136},
            "description.ko": {"str": 136},
            "description.ru": {"str": 136},
            "description.zh": {"str": 136},
            "groupID": {"int": 136},
            "name": {"dict": 136},
            "name.de": {"str": 136},
            "name.en": {"str": 136},
            "name.es": {"str": 136},
            "name.fr": {"str": 136},
            "name.ja": {"str": 136},
            "name.ko": {"str": 136},
            "name.ru": {"str": 136},
            "name.zh": {"str": 136},
            "recommendedFor": {"list": 81},
            "skillTypes": {"dict": 886, "list": 136},
            "skillTypes._key": {"int": 886},
            "skillTypes.advanced": {"int": 886},
            "skillTypes.basic": {"int": 886},
            "skillTypes.elite": {"int": 886},
            "skillTypes.improved": {"int": 886},
            "skillTypes.standard": {"int": 886},
        },
        "source_info": "certificates.jsonl (build 3201939)",
    },
    "characterAttributes.jsonl": {
        "dict_count": 5,
        "key_info": {
            "_key": {"int": 5},
            "description": {"str": 5},
            "iconID": {"int": 5},
            "name": {"dict": 5},
            "name.de": {"str": 5},
            "name.en": {"str": 5},
            "name.es": {"str": 5},
            "name.fr": {"str": 5},
            "name.ja": {"str": 5},
            "name.ko": {"str": 5},
            "name.ru": {"str": 5},
            "name.zh": {"str": 5},
            "notes": {"str": 5},
            "shortDescription": {"str": 5},
        },
        "source_info": "characterAttributes.jsonl (build 3201939)",
    },
    "cloneGrades.jsonl": {
        "dict_count": 4,
        "key_info": {
            "_key": {"int": 4},
            "name": {"str": 4},
            "skills": {"dict": 700, "list": 4},
            "skills.level": {"int": 700},
            "skills.typeID": {"int": 700},
        },
        "source_info": "cloneGrades.jsonl (build 3201939)",
    },
    "compressibleTypes.jsonl": {
        "dict_count": 206,
        "key_info": {"_key": {"int": 206}, "compressedTypeID": {"int": 206}},
        "source_info": "compressibleTypes.jsonl (build 3201939)",
    },
    "contrabandTypes.jsonl": {
        "dict_count": 8,
        "key_info": {
            "_key": {"int": 8},
            "factions": {"dict": 50, "list": 8},
            "factions._key": {"int": 50},
            "factions.attackMinSec": {"float": 50},
            "factions.confiscateMinSec": {"float": 50},
            "factions.fineByValue": {"float": 50},
            "factions.standingLoss": {"float": 50},
        },
        "source_info": "contrabandTypes.jsonl (build 3201939)",
    },
    "controlTowerResources.jsonl": {
        "dict_count": 44,
        "key_info": {
            "_key": {"int": 44},
            "resources": {"dict": 339, "list": 44},
            "resources.factionID": {"int": 252},
            "resources.minSecurityLevel": {"float": 252},
            "resources.purpose": {"int": 339},
            "resources.quantity": {"int": 339},
            "resources.resourceTypeID": {"int": 339},
        },
        "source_info": "controlTowerResources.jsonl (build 3201939)",
    },
    "corporationActivities.jsonl": {
        "dict_count": 20,
        "key_info": {
            "_key": {"int": 20},
            "name": {"dict": 20},
            "name.de": {"str": 20},
            "name.en": {"str": 20},
            "name.es": {"str": 20},
            "name.fr": {"str": 20},
            "name.ja": {"str": 20},
            "name.ko": {"str": 20},
            "name.ru": {"str": 20},
            "name.zh": {"str": 20},
        },
        "source_info": "corporationActivities.jsonl (build 3201939)",
    },
    "dbuffCollections.jsonl": {
        "dict_count": 206,
        "key_info": {
            "_key": {"int": 206},
            "aggregateMode": {"str": 206},
            "developerDescription": {"str": 206},
            "displayName": {"dict": 188},
            "displayName.de": {"str": 188},
            "displayName.en": {"str": 188},
            "displayName.es": {"str": 188},
            "displayName.fr": {"str": 188},
            "displayName.ja": {"str": 188},
            "displayName.ko": {"str": 188},
            "displayName.ru": {"str": 188},
            "displayName.zh": {"str": 188},
            "itemModifiers": {"dict": 187, "list": 120},
            "itemModifiers.dogmaAttributeID": {"int": 187},
            "locationGroupModifiers": {"dict": 36, "list": 11},
            "locationGroupModifiers.dogmaAttributeID": {"int": 36},
            "locationGroupModifiers.groupID": {"int": 36},
            "locationModifiers": {"dict": 33, "list": 9},
            "locationModifiers.dogmaAttributeID": {"int": 33},
            "locationRequiredSkillModifiers": {"dict": 111, "list": 65},
            "locationRequiredSkillModifiers.dogmaAttributeID": {"int": 111},
            "locationRequiredSkillModifiers.skillID": {"int": 111},
            "operationName": {"str": 206},
            "showOutputValueInUI": {"str": 206},
        },
        "source_info": "dbuffCollections.jsonl (build 3201939)",
    },
    "dogmaAttributeCategories.jsonl": {
        "dict_count": 37,
        "key_info": {
            "_key": {"int": 37},
            "description": {"str": 36},
            "name": {"str": 37},
        },
        "source_info": "dogmaAttributeCategories.jsonl (build 3201939)",
    },
    "dogmaAttributes.jsonl": {
        "dict_count": 2825,
        "key_info": {
            "_key": {"int": 2825},
            "attributeCategoryID": {"int": 2641},
            "chargeRechargeTimeID": {"int": 6},
            "dataType": {"int": 2825},
            "defaultValue": {"float": 2825},
            "description": {"str": 2623},
            "displayName": {"dict": 1233},
            "displayName.de": {"str": 1233},
            "displayName.en": {"str": 1233},
            "displayName.es": {"str": 1233},
            "displayName.fr": {"str": 1233},
            "displayName.ja": {"str": 1233},
            "displayName.ko": {"str": 1233},
            "displayName.ru": {"str": 1233},
            "displayName.zh": {"str": 1233},
            "displayWhenZero": {"bool": 2825},
            "highIsGood": {"bool": 2825},
            "iconID": {"int": 1350},
            "maxAttributeID": {"int": 29},
            "minAttributeID": {"int": 3},
            "name": {"str": 2825},
            "published": {"bool": 2825},
            "stackable": {"bool": 2825},
            "tooltipDescription": {"dict": 68},
            "tooltipDescription.de": {"str": 68},
            "tooltipDescription.en": {"str": 68},
            "tooltipDescription.es": {"str": 68},
            "tooltipDescription.fr": {"str": 68},
            "tooltipDescription.ja": {"str": 68},
            "tooltipDescription.ko": {"str": 68},
            "tooltipDescription.ru": {"str": 68},
            "tooltipDescription.zh": {"str": 68},
            "tooltipTitle": {"dict": 70},
            "tooltipTitle.de": {"str": 70},
            "tooltipTitle.en": {"str": 70},
            "tooltipTitle.es": {"str": 70},
            "tooltipTitle.fr": {"str": 70},
            "tooltipTitle.ja": {"str": 70},
            "tooltipTitle.ko": {"str": 70},
            "tooltipTitle.ru": {"str": 70},
            "tooltipTitle.zh": {"str": 70},
            "unitID": {"int": 1336},
        },
        "source_info": "dogmaAttributes.jsonl (build 3201939)",
    },
    "dogmaEffects.jsonl": {
        "dict_count": 3356,
        "key_info": {
            "_key": {"int": 3356},
            "description": {"dict": 753},
            "description.de": {"str": 753},
            "description.en": {"str": 753},
            "description.es": {"str": 753},
            "description.fr": {"str": 753},
            "description.ja": {"str": 753},
            "description.ko": {"str": 753},
            "description.ru": {"str": 753},
            "description.zh": {"str": 753},
            "disallowAutoRepeat": {"bool": 3356},
            "dischargeAttributeID": {"int": 171},
            "displayName": {"dict": 70},
            "displayName.de": {"str": 70},
            "displayName.en": {"str": 70},
            "displayName.es": {"str": 70},
            "displayName.fr": {"str": 70},
            "displayName.ja": {"str": 70},
            "displayName.ko": {"str": 70},
            "displayName.ru": {"str": 70},
            "displayName.zh": {"str": 70},
            "distribution": {"int": 75},
            "durationAttributeID": {"int": 223},
            "effectCategoryID": {"int": 3356},
            "electronicChance": {"bool": 3356},
            "falloffAttributeID": {"int": 51},
            "fittingUsageChanceAttributeID": {"int": 12},
            "guid": {"str": 1630},
            "iconID": {"int": 1268},
            "isAssistance": {"bool": 3356},
            "isOffensive": {"bool": 3356},
            "isWarpSafe": {"bool": 3356},
            "modifierInfo": {"dict": 5001, "list": 3140},
            "modifierInfo.domain": {"str": 5001},
            "modifierInfo.effectID": {"int": 10},
            "modifierInfo.func": {"str": 5001},
            "modifierInfo.groupID": {"int": 791},
            "modifierInfo.modifiedAttributeID": {"int": 4991},
            "modifierInfo.modifyingAttributeID": {"int": 4991},
            "modifierInfo.operation": {"int": 4991},
            "modifierInfo.skillTypeID": {"int": 2418},
            "name": {"str": 3356},
            "npcActivationChanceAttributeID": {"int": 19},
            "npcUsageChanceAttributeID": {"int": 7},
            "propulsionChance": {"bool": 3356},
            "published": {"bool": 3356},
            "rangeAttributeID": {"int": 225},
            "rangeChance": {"bool": 3356},
            "resistanceAttributeID": {"int": 39},
            "trackingSpeedAttributeID": {"int": 6},
        },
        "source_info": "dogmaEffects.jsonl (build 3201939)",
    },
    "dogmaUnits.jsonl": {
        "dict_count": 60,
        "key_info": {
            "_key": {"int": 60},
            "description": {"dict": 44},
            "description.de": {"str": 44},
            "description.en": {"str": 44},
            "description.es": {"str": 44},
            "description.fr": {"str": 44},
            "description.ja": {"str": 44},
            "description.ko": {"str": 44},
            "description.ru": {"str": 44},
            "description.zh": {"str": 44},
            "displayName": {"dict": 56},
            "displayName.de": {"str": 56},
            "displayName.en": {"str": 56},
            "displayName.es": {"str": 56},
            "displayName.fr": {"str": 56},
            "displayName.ja": {"str": 56},
            "displayName.ko": {"str": 56},
            "displayName.ru": {"str": 56},
            "displayName.zh": {"str": 56},
            "name": {"str": 60},
        },
        "source_info": "dogmaUnits.jsonl (build 3201939)",
    },
    "dynamicItemAttributes.jsonl": {
        "dict_count": 413,
        "key_info": {
            "_key": {"int": 413},
            "attributeIDs": {"dict": 2124, "list": 413},
            "attributeIDs._key": {"int": 2124},
            "attributeIDs.highIsGood": {"bool": 12},
            "attributeIDs.max": {"float": 2124},
            "attributeIDs.min": {"float": 2124},
            "inputOutputMapping": {"dict": 413, "list": 413},
            "inputOutputMapping.applicableTypes": {"list": 413},
            "inputOutputMapping.resultingType": {"int": 413},
        },
        "source_info": "dynamicItemAttributes.jsonl (build 3201939)",
    },
    "factions.jsonl": {
        "dict_count": 27,
        "key_info": {
            "_key": {"int": 27},
            "corporationID": {"int": 26},
            "description": {"dict": 27},
            "description.de": {"str": 27},
            "description.en": {"str": 27},
            "description.es": {"str": 27},
            "description.fr": {"str": 27},
            "description.ja": {"str": 27},
            "description.ko": {"str": 27},
            "description.ru": {"str": 27},
            "description.zh": {"str": 27},
            "flatLogo": {"str": 18},
            "flatLogoWithName": {"str": 6},
            "iconID": {"int": 27},
            "memberRaces": {"list": 27},
            "militiaCorporationID": {"int": 6},
            "name": {"dict": 27},
            "name.de": {"str": 27},
            "name.en": {"str": 27},
            "name.es": {"str": 27},
            "name.fr": {"str": 27},
            "name.ja": {"str": 27},
            "name.ko": {"str": 27},
            "name.ru": {"str": 27},
            "name.zh": {"str": 27},
            "shortDescription": {"dict": 4},
            "shortDescription.de": {"str": 4},
            "shortDescription.en": {"str": 4},
            "shortDescription.es": {"str": 4},
            "shortDescription.fr": {"str": 4},
            "shortDescription.ja": {"str": 4},
            "shortDescription.ko": {"str": 4},
            "shortDescription.ru": {"str": 4},
            "shortDescription.zh": {"str": 4},
            "sizeFactor": {"float": 27},
            "solarSystemID": {"int": 27},
            "uniqueName": {"bool": 27},
        },
        "source_info": "factions.jsonl (build 3201939)",
    },
    "freelanceJobSchemas.jsonl": {
        "dict_count": 1,
        "key_info": {
            "_key": {"int": 1},
            "_value": {"dict": 10, "list": 1},
            "_value._key": {"str": 10},
            "_value.contentTags": {"list": 10},
            "_value.contributionMultiplier": {"dict": 1},
            "_value.contributionMultiplier.defaultValue": {"int": 1},
            "_value.contributionMultiplier.description": {"dict": 1},
            "_value.contributionMultiplier.description.de": {"str": 1},
            "_value.contributionMultiplier.description.en": {"str": 1},
            "_value.contributionMultiplier.description.es": {"str": 1},
            "_value.contributionMultiplier.description.fr": {"str": 1},
            "_value.contributionMultiplier.description.ja": {"str": 1},
            "_value.contributionMultiplier.description.ko": {"str": 1},
            "_value.contributionMultiplier.description.ru": {"str": 1},
            "_value.contributionMultiplier.description.zh": {"str": 1},
            "_value.contributionMultiplier.iconID": {"str": 1},
            "_value.contributionMultiplier.maxValue": {"int": 1},
            "_value.contributionMultiplier.minValue": {"float": 1},
            "_value.contributionMultiplier.title": {"dict": 1},
            "_value.contributionMultiplier.title.de": {"str": 1},
            "_value.contributionMultiplier.title.en": {"str": 1},
            "_value.contributionMultiplier.title.es": {"str": 1},
            "_value.contributionMultiplier.title.fr": {"str": 1},
            "_value.contributionMultiplier.title.ja": {"str": 1},
            "_value.contributionMultiplier.title.ko": {"str": 1},
            "_value.contributionMultiplier.title.ru": {"str": 1},
            "_value.contributionMultiplier.title.zh": {"str": 1},
            "_value.contributionMultiplier.unsetDescription": {"dict": 1},
            "_value.contributionMultiplier.unsetDescription.de": {"str": 1},
            "_value.contributionMultiplier.unsetDescription.en": {"str": 1},
            "_value.contributionMultiplier.unsetDescription.es": {"str": 1},
            "_value.contributionMultiplier.unsetDescription.fr": {"str": 1},
            "_value.contributionMultiplier.unsetDescription.ja": {"str": 1},
            "_value.contributionMultiplier.unsetDescription.ko": {"str": 1},
            "_value.contributionMultiplier.unsetDescription.ru": {"str": 1},
            "_value.contributionMultiplier.unsetDescription.zh": {"str": 1},
            "_value.description": {"dict": 10},
            "_value.description.de": {"str": 10},
            "_value.description.en": {"str": 10},
            "_value.description.es": {"str": 10},
            "_value.description.fr": {"str": 10},
            "_value.description.ja": {"str": 10},
            "_value.description.ko": {"str": 10},
            "_value.description.ru": {"str": 10},
            "_value.description.zh": {"str": 10},
            "_value.iconID": {"str": 10},
            "_value.maxContributionsPerParticipant": {"dict": 10},
            "_value.maxContributionsPerParticipant.description": {"dict": 10},
            "_value.maxContributionsPerParticipant.description.de": {"str": 10},
            "_value.maxContributionsPerParticipant.description.en": {"str": 10},
            "_value.maxContributionsPerParticipant.description.es": {"str": 10},
            "_value.maxContributionsPerParticipant.description.fr": {"str": 10},
            "_value.maxContributionsPerParticipant.description.ja": {"str": 10},
            "_value.maxContributionsPerParticipant.description.ko": {"str": 10},
            "_value.maxContributionsPerParticipant.description.ru": {"str": 10},
            "_value.maxContributionsPerParticipant.description.zh": {"str": 10},
            "_value.maxContributionsPerParticipant.iconID": {"str": 10},
            "_value.maxContributionsPerParticipant.title": {"dict": 10},
            "_value.maxContributionsPerParticipant.title.de": {"str": 10},
            "_value.maxContributionsPerParticipant.title.en": {"str": 10},
            "_value.maxContributionsPerParticipant.title.es": {"str": 10},
            "_value.maxContributionsPerParticipant.title.fr": {"str": 10},
            "_value.maxContributionsPerParticipant.title.ja": {"str": 10},
            "_value.maxContributionsPerParticipant.title.ko": {"str": 10},
            "_value.maxContributionsPerParticipant.title.ru": {"str": 10},
            "_value.maxContributionsPerParticipant.title.zh": {"str": 10},
            "_value.maxContributionsPerParticipant.unsetDescription": {"dict": 10},
            "_value.maxContributionsPerParticipant.unsetDescription.de": {"str": 10},
            "_value.maxContributionsPerParticipant.unsetDescription.en": {"str": 10},
            "_value.maxContributionsPerParticipant.unsetDescription.es": {"str": 10},
            "_value.maxContributionsPerParticipant.unsetDescription.fr": {"str": 10},
            "_value.maxContributionsPerParticipant.unsetDescription.ja": {"str": 10},
            "_value.maxContributionsPerParticipant.unsetDescription.ko": {"str": 10},
            "_value.maxContributionsPerParticipant.unsetDescription.ru": {"str": 10},
            "_value.maxContributionsPerParticipant.unsetDescription.zh": {"str": 10},
            "_value.maxProgressPerContribution": {"dict": 1},
            "_value.maxProgressPerContribution.description": {"dict": 1},
            "_value.maxProgressPerContribution.description.de": {"str": 1},
            "_value.maxProgressPerContribution.description.en": {"str": 1},
            "_value.maxProgressPerContribution.description.es": {"str": 1},
            "_value.maxProgressPerContribution.description.fr": {"str": 1},
            "_value.maxProgressPerContribution.description.ja": {"str": 1},
            "_value.maxProgressPerContribution.description.ko": {"str": 1},
            "_value.maxProgressPerContribution.description.ru": {"str": 1},
            "_value.maxProgressPerContribution.description.zh": {"str": 1},
            "_value.maxProgressPerContribution.iconID": {"str": 1},
            "_value.maxProgressPerContribution.title": {"dict": 1},
            "_value.maxProgressPerContribution.title.de": {"str": 1},
            "_value.maxProgressPerContribution.title.en": {"str": 1},
            "_value.maxProgressPerContribution.title.es": {"str": 1},
            "_value.maxProgressPerContribution.title.fr": {"str": 1},
            "_value.maxProgressPerContribution.title.ja": {"str": 1},
            "_value.maxProgressPerContribution.title.ko": {"str": 1},
            "_value.maxProgressPerContribution.title.ru": {"str": 1},
            "_value.maxProgressPerContribution.title.zh": {"str": 1},
            "_value.maxProgressPerContribution.unsetDescription": {"dict": 1},
            "_value.maxProgressPerContribution.unsetDescription.de": {"str": 1},
            "_value.maxProgressPerContribution.unsetDescription.en": {"str": 1},
            "_value.maxProgressPerContribution.unsetDescription.es": {"str": 1},
            "_value.maxProgressPerContribution.unsetDescription.fr": {"str": 1},
            "_value.maxProgressPerContribution.unsetDescription.ja": {"str": 1},
            "_value.maxProgressPerContribution.unsetDescription.ko": {"str": 1},
            "_value.maxProgressPerContribution.unsetDescription.ru": {"str": 1},
            "_value.maxProgressPerContribution.unsetDescription.zh": {"str": 1},
            "_value.parameters": {"dict": 27, "list": 10},
            "_value.parameters._key": {"str": 27},
            "_value.parameters.boolean": {"dict": 2},
            "_value.parameters.boolean.choiceLabel": {"dict": 2},
            "_value.parameters.boolean.choiceLabel.de": {"str": 2},
            "_value.parameters.boolean.choiceLabel.en": {"str": 2},
            "_value.parameters.boolean.choiceLabel.es": {"str": 2},
            "_value.parameters.boolean.choiceLabel.fr": {"str": 2},
            "_value.parameters.boolean.choiceLabel.ja": {"str": 2},
            "_value.parameters.boolean.choiceLabel.ko": {"str": 2},
            "_value.parameters.boolean.choiceLabel.ru": {"str": 2},
            "_value.parameters.boolean.choiceLabel.zh": {"str": 2},
            "_value.parameters.boolean.default": {"bool": 2},
            "_value.parameters.boolean.description": {"dict": 2},
            "_value.parameters.boolean.description.de": {"str": 2},
            "_value.parameters.boolean.description.en": {"str": 2},
            "_value.parameters.boolean.description.es": {"str": 2},
            "_value.parameters.boolean.description.fr": {"str": 2},
            "_value.parameters.boolean.description.ja": {"str": 2},
            "_value.parameters.boolean.description.ko": {"str": 2},
            "_value.parameters.boolean.description.ru": {"str": 2},
            "_value.parameters.boolean.description.zh": {"str": 2},
            "_value.parameters.boolean.iconID": {"str": 2},
            "_value.parameters.boolean.optionFalse": {"dict": 2},
            "_value.parameters.boolean.optionFalse.description": {"dict": 2},
            "_value.parameters.boolean.optionFalse.description.de": {"str": 2},
            "_value.parameters.boolean.optionFalse.description.en": {"str": 2},
            "_value.parameters.boolean.optionFalse.description.es": {"str": 2},
            "_value.parameters.boolean.optionFalse.description.fr": {"str": 2},
            "_value.parameters.boolean.optionFalse.description.ja": {"str": 2},
            "_value.parameters.boolean.optionFalse.description.ko": {"str": 2},
            "_value.parameters.boolean.optionFalse.description.ru": {"str": 2},
            "_value.parameters.boolean.optionFalse.description.zh": {"str": 2},
            "_value.parameters.boolean.optionFalse.title": {"dict": 2},
            "_value.parameters.boolean.optionFalse.title.de": {"str": 2},
            "_value.parameters.boolean.optionFalse.title.en": {"str": 2},
            "_value.parameters.boolean.optionFalse.title.es": {"str": 2},
            "_value.parameters.boolean.optionFalse.title.fr": {"str": 2},
            "_value.parameters.boolean.optionFalse.title.ja": {"str": 2},
            "_value.parameters.boolean.optionFalse.title.ko": {"str": 2},
            "_value.parameters.boolean.optionFalse.title.ru": {"str": 2},
            "_value.parameters.boolean.optionFalse.title.zh": {"str": 2},
            "_value.parameters.boolean.optionTrue": {"dict": 2},
            "_value.parameters.boolean.optionTrue.description": {"dict": 2},
            "_value.parameters.boolean.optionTrue.description.de": {"str": 2},
            "_value.parameters.boolean.optionTrue.description.en": {"str": 2},
            "_value.parameters.boolean.optionTrue.description.es": {"str": 2},
            "_value.parameters.boolean.optionTrue.description.fr": {"str": 2},
            "_value.parameters.boolean.optionTrue.description.ja": {"str": 2},
            "_value.parameters.boolean.optionTrue.description.ko": {"str": 2},
            "_value.parameters.boolean.optionTrue.description.ru": {"str": 2},
            "_value.parameters.boolean.optionTrue.description.zh": {"str": 2},
            "_value.parameters.boolean.optionTrue.title": {"dict": 2},
            "_value.parameters.boolean.optionTrue.title.de": {"str": 2},
            "_value.parameters.boolean.optionTrue.title.en": {"str": 2},
            "_value.parameters.boolean.optionTrue.title.es": {"str": 2},
            "_value.parameters.boolean.optionTrue.title.fr": {"str": 2},
            "_value.parameters.boolean.optionTrue.title.ja": {"str": 2},
            "_value.parameters.boolean.optionTrue.title.ko": {"str": 2},
            "_value.parameters.boolean.optionTrue.title.ru": {"str": 2},
            "_value.parameters.boolean.optionTrue.title.zh": {"str": 2},
            "_value.parameters.boolean.title": {"dict": 2},
            "_value.parameters.boolean.title.de": {"str": 2},
            "_value.parameters.boolean.title.en": {"str": 2},
            "_value.parameters.boolean.title.es": {"str": 2},
            "_value.parameters.boolean.title.fr": {"str": 2},
            "_value.parameters.boolean.title.ja": {"str": 2},
            "_value.parameters.boolean.title.ko": {"str": 2},
            "_value.parameters.boolean.title.ru": {"str": 2},
            "_value.parameters.boolean.title.zh": {"str": 2},
            "_value.parameters.itemDelivery": {"dict": 1},
            "_value.parameters.itemDelivery.deliveryLocation": {"dict": 1},
            "_value.parameters.itemDelivery.deliveryLocation.acceptedValueTypes": {
                "list": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.description": {"dict": 1},
            "_value.parameters.itemDelivery.deliveryLocation.description.de": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.description.en": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.description.es": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.description.fr": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.description.ja": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.description.ko": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.description.ru": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.description.zh": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.iconID": {"str": 1},
            "_value.parameters.itemDelivery.deliveryLocation.maxEntries": {"int": 1},
            "_value.parameters.itemDelivery.deliveryLocation.title": {"dict": 1},
            "_value.parameters.itemDelivery.deliveryLocation.title.de": {"str": 1},
            "_value.parameters.itemDelivery.deliveryLocation.title.en": {"str": 1},
            "_value.parameters.itemDelivery.deliveryLocation.title.es": {"str": 1},
            "_value.parameters.itemDelivery.deliveryLocation.title.fr": {"str": 1},
            "_value.parameters.itemDelivery.deliveryLocation.title.ja": {"str": 1},
            "_value.parameters.itemDelivery.deliveryLocation.title.ko": {"str": 1},
            "_value.parameters.itemDelivery.deliveryLocation.title.ru": {"str": 1},
            "_value.parameters.itemDelivery.deliveryLocation.title.zh": {"str": 1},
            "_value.parameters.itemDelivery.deliveryLocation.unsetDescription": {
                "dict": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.unsetDescription.de": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.unsetDescription.en": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.unsetDescription.es": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.unsetDescription.fr": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.unsetDescription.ja": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.unsetDescription.ko": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.unsetDescription.ru": {
                "str": 1
            },
            "_value.parameters.itemDelivery.deliveryLocation.unsetDescription.zh": {
                "str": 1
            },
            "_value.parameters.itemDelivery.description": {"dict": 1},
            "_value.parameters.itemDelivery.description.de": {"str": 1},
            "_value.parameters.itemDelivery.description.en": {"str": 1},
            "_value.parameters.itemDelivery.description.es": {"str": 1},
            "_value.parameters.itemDelivery.description.fr": {"str": 1},
            "_value.parameters.itemDelivery.description.ja": {"str": 1},
            "_value.parameters.itemDelivery.description.ko": {"str": 1},
            "_value.parameters.itemDelivery.description.ru": {"str": 1},
            "_value.parameters.itemDelivery.description.zh": {"str": 1},
            "_value.parameters.itemDelivery.iconID": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType": {"dict": 1},
            "_value.parameters.itemDelivery.inventoryType.acceptedValueTypes": {
                "list": 1
            },
            "_value.parameters.itemDelivery.inventoryType.description": {"dict": 1},
            "_value.parameters.itemDelivery.inventoryType.description.de": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.description.en": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.description.es": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.description.fr": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.description.ja": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.description.ko": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.description.ru": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.description.zh": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.iconID": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.title": {"dict": 1},
            "_value.parameters.itemDelivery.inventoryType.title.de": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.title.en": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.title.es": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.title.fr": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.title.ja": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.title.ko": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.title.ru": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.title.zh": {"str": 1},
            "_value.parameters.itemDelivery.inventoryType.unsetDescription": {
                "dict": 1
            },
            "_value.parameters.itemDelivery.inventoryType.unsetDescription.de": {
                "str": 1
            },
            "_value.parameters.itemDelivery.inventoryType.unsetDescription.en": {
                "str": 1
            },
            "_value.parameters.itemDelivery.inventoryType.unsetDescription.es": {
                "str": 1
            },
            "_value.parameters.itemDelivery.inventoryType.unsetDescription.fr": {
                "str": 1
            },
            "_value.parameters.itemDelivery.inventoryType.unsetDescription.ja": {
                "str": 1
            },
            "_value.parameters.itemDelivery.inventoryType.unsetDescription.ko": {
                "str": 1
            },
            "_value.parameters.itemDelivery.inventoryType.unsetDescription.ru": {
                "str": 1
            },
            "_value.parameters.itemDelivery.inventoryType.unsetDescription.zh": {
                "str": 1
            },
            "_value.parameters.itemDelivery.title": {"dict": 1},
            "_value.parameters.itemDelivery.title.de": {"str": 1},
            "_value.parameters.itemDelivery.title.en": {"str": 1},
            "_value.parameters.itemDelivery.title.es": {"str": 1},
            "_value.parameters.itemDelivery.title.fr": {"str": 1},
            "_value.parameters.itemDelivery.title.ja": {"str": 1},
            "_value.parameters.itemDelivery.title.ko": {"str": 1},
            "_value.parameters.itemDelivery.title.ru": {"str": 1},
            "_value.parameters.itemDelivery.title.zh": {"str": 1},
            "_value.parameters.matcher": {"dict": 24},
            "_value.parameters.matcher.acceptedValueTypes": {"list": 24},
            "_value.parameters.matcher.description": {"dict": 24},
            "_value.parameters.matcher.description.de": {"str": 24},
            "_value.parameters.matcher.description.en": {"str": 24},
            "_value.parameters.matcher.description.es": {"str": 24},
            "_value.parameters.matcher.description.fr": {"str": 24},
            "_value.parameters.matcher.description.ja": {"str": 24},
            "_value.parameters.matcher.description.ko": {"str": 24},
            "_value.parameters.matcher.description.ru": {"str": 24},
            "_value.parameters.matcher.description.zh": {"str": 24},
            "_value.parameters.matcher.iconID": {"str": 24},
            "_value.parameters.matcher.maxEntries": {"int": 24},
            "_value.parameters.matcher.optional": {"bool": 24},
            "_value.parameters.matcher.title": {"dict": 24},
            "_value.parameters.matcher.title.de": {"str": 24},
            "_value.parameters.matcher.title.en": {"str": 24},
            "_value.parameters.matcher.title.es": {"str": 24},
            "_value.parameters.matcher.title.fr": {"str": 24},
            "_value.parameters.matcher.title.ja": {"str": 24},
            "_value.parameters.matcher.title.ko": {"str": 24},
            "_value.parameters.matcher.title.ru": {"str": 24},
            "_value.parameters.matcher.title.zh": {"str": 24},
            "_value.parameters.matcher.type": {"str": 24},
            "_value.parameters.matcher.unsetDescription": {"dict": 24},
            "_value.parameters.matcher.unsetDescription.de": {"str": 24},
            "_value.parameters.matcher.unsetDescription.en": {"str": 24},
            "_value.parameters.matcher.unsetDescription.es": {"str": 24},
            "_value.parameters.matcher.unsetDescription.fr": {"str": 24},
            "_value.parameters.matcher.unsetDescription.ja": {"str": 24},
            "_value.parameters.matcher.unsetDescription.ko": {"str": 24},
            "_value.parameters.matcher.unsetDescription.ru": {"str": 24},
            "_value.parameters.matcher.unsetDescription.zh": {"str": 24},
            "_value.progressDescription": {"dict": 10},
            "_value.progressDescription.de": {"str": 10},
            "_value.progressDescription.en": {"str": 10},
            "_value.progressDescription.es": {"str": 10},
            "_value.progressDescription.fr": {"str": 10},
            "_value.progressDescription.ja": {"str": 10},
            "_value.progressDescription.ko": {"str": 10},
            "_value.progressDescription.ru": {"str": 10},
            "_value.progressDescription.zh": {"str": 10},
            "_value.rewardDescription": {"dict": 10},
            "_value.rewardDescription.de": {"str": 10},
            "_value.rewardDescription.en": {"str": 10},
            "_value.rewardDescription.es": {"str": 10},
            "_value.rewardDescription.fr": {"str": 10},
            "_value.rewardDescription.ja": {"str": 10},
            "_value.rewardDescription.ko": {"str": 10},
            "_value.rewardDescription.ru": {"str": 10},
            "_value.rewardDescription.zh": {"str": 10},
            "_value.targetDescription": {"dict": 10},
            "_value.targetDescription.de": {"str": 10},
            "_value.targetDescription.en": {"str": 10},
            "_value.targetDescription.es": {"str": 10},
            "_value.targetDescription.fr": {"str": 10},
            "_value.targetDescription.ja": {"str": 10},
            "_value.targetDescription.ko": {"str": 10},
            "_value.targetDescription.ru": {"str": 10},
            "_value.targetDescription.zh": {"str": 10},
            "_value.title": {"dict": 10},
            "_value.title.de": {"str": 10},
            "_value.title.en": {"str": 10},
            "_value.title.es": {"str": 10},
            "_value.title.fr": {"str": 10},
            "_value.title.ja": {"str": 10},
            "_value.title.ko": {"str": 10},
            "_value.title.ru": {"str": 10},
            "_value.title.zh": {"str": 10},
        },
        "source_info": "freelanceJobSchemas.jsonl (build 3201939)",
    },
    "graphics.jsonl": {
        "dict_count": 5549,
        "key_info": {
            "_key": {"int": 5549},
            "graphicFile": {"str": 2369},
            "iconFolder": {"str": 2584},
            "sofFactionName": {"str": 3686},
            "sofHullName": {"str": 3108},
            "sofLayout": {"list": 53},
            "sofMaterialSetID": {"int": 96},
            "sofRaceName": {"str": 3881},
        },
        "source_info": "graphics.jsonl (build 3201939)",
    },
    "groups.jsonl": {
        "dict_count": 1578,
        "key_info": {
            "_key": {"int": 1578},
            "anchorable": {"bool": 1578},
            "anchored": {"bool": 1578},
            "categoryID": {"int": 1578},
            "fittableNonSingleton": {"bool": 1578},
            "iconID": {"int": 765},
            "name": {"dict": 1578},
            "name.de": {"str": 1578},
            "name.en": {"str": 1578},
            "name.es": {"str": 1578},
            "name.fr": {"str": 1578},
            "name.ja": {"str": 1578},
            "name.ko": {"str": 1578},
            "name.ru": {"str": 1578},
            "name.zh": {"str": 1578},
            "published": {"bool": 1578},
            "useBasePrice": {"bool": 1578},
        },
        "source_info": "groups.jsonl (build 3201939)",
    },
    "icons.jsonl": {
        "dict_count": 4452,
        "key_info": {"_key": {"int": 4452}, "iconFile": {"str": 4452}},
        "source_info": "icons.jsonl (build 3201939)",
    },
    "landmarks.jsonl": {
        "dict_count": 45,
        "key_info": {
            "_key": {"int": 45},
            "description": {"dict": 45},
            "description.de": {"str": 45},
            "description.en": {"str": 45},
            "description.es": {"str": 45},
            "description.fr": {"str": 45},
            "description.ja": {"str": 45},
            "description.ko": {"str": 45},
            "description.ru": {"str": 45},
            "description.zh": {"str": 45},
            "iconID": {"int": 19},
            "locationID": {"int": 10},
            "name": {"dict": 45},
            "name.de": {"str": 45},
            "name.en": {"str": 45},
            "name.es": {"str": 45},
            "name.fr": {"str": 45},
            "name.ja": {"str": 45},
            "name.ko": {"str": 45},
            "name.ru": {"str": 45},
            "name.zh": {"str": 45},
            "position": {"dict": 45},
            "position.x": {"float": 45},
            "position.y": {"float": 45},
            "position.z": {"float": 45},
        },
        "source_info": "landmarks.jsonl (build 3201939)",
    },
    "mapAsteroidBelts.jsonl": {
        "dict_count": 40928,
        "key_info": {
            "_key": {"int": 40928},
            "celestialIndex": {"int": 40928},
            "orbitID": {"int": 40928},
            "orbitIndex": {"int": 40928},
            "position": {"dict": 40928},
            "position.x": {"float": 40928},
            "position.y": {"float": 40928},
            "position.z": {"float": 40928},
            "radius": {"float": 40226},
            "solarSystemID": {"int": 40928},
            "statistics": {"dict": 40226},
            "statistics.density": {"float": 40226},
            "statistics.eccentricity": {"float": 40226},
            "statistics.escapeVelocity": {"float": 40226},
            "statistics.locked": {"bool": 40226},
            "statistics.massDust": {"float": 40226},
            "statistics.massGas": {"float": 24847},
            "statistics.orbitPeriod": {"float": 40226},
            "statistics.orbitRadius": {"float": 40226},
            "statistics.rotationRate": {"float": 40226},
            "statistics.spectralClass": {"str": 40226},
            "statistics.surfaceGravity": {"float": 40226},
            "statistics.temperature": {"float": 40226},
            "typeID": {"int": 40928},
            "uniqueName": {"dict": 46},
            "uniqueName.de": {"str": 46},
            "uniqueName.en": {"str": 46},
            "uniqueName.es": {"str": 46},
            "uniqueName.fr": {"str": 46},
            "uniqueName.ja": {"str": 46},
            "uniqueName.ko": {"str": 46},
            "uniqueName.ru": {"str": 46},
            "uniqueName.zh": {"str": 46},
        },
        "source_info": "mapAsteroidBelts.jsonl (build 3201939)",
    },
    "mapConstellations.jsonl": {
        "dict_count": 1175,
        "key_info": {
            "_key": {"int": 1175},
            "factionID": {"int": 377},
            "name": {"dict": 1175},
            "name.de": {"str": 1175},
            "name.en": {"str": 1175},
            "name.es": {"str": 1175},
            "name.fr": {"str": 1175},
            "name.ja": {"str": 1175},
            "name.ko": {"str": 1175},
            "name.ru": {"str": 1175},
            "name.zh": {"str": 1175},
            "position": {"dict": 1175},
            "position.x": {"float": 1175},
            "position.y": {"float": 1175},
            "position.z": {"float": 1175},
            "regionID": {"int": 1175},
            "solarSystemIDs": {"list": 1175},
            "wormholeClassID": {"int": 1141},
        },
        "source_info": "mapConstellations.jsonl (build 3201939)",
    },
    "mapMoons.jsonl": {
        "dict_count": 342170,
        "key_info": {
            "_key": {"int": 342170},
            "attributes": {"dict": 342170},
            "attributes.heightMap1": {"int": 342170},
            "attributes.heightMap2": {"int": 342170},
            "attributes.shaderPreset": {"int": 342170},
            "celestialIndex": {"int": 342170},
            "npcStationIDs": {"list": 3801},
            "orbitID": {"int": 342170},
            "orbitIndex": {"int": 342170},
            "position": {"dict": 342170},
            "position.x": {"float": 342170},
            "position.y": {"float": 342170},
            "position.z": {"float": 342170},
            "radius": {"float": 342170},
            "solarSystemID": {"int": 342170},
            "statistics": {"dict": 340806},
            "statistics.density": {"float": 340806},
            "statistics.eccentricity": {"float": 340806},
            "statistics.escapeVelocity": {"float": 340806},
            "statistics.locked": {"bool": 340806},
            "statistics.massDust": {"float": 340806},
            "statistics.massGas": {"float": 340805},
            "statistics.orbitPeriod": {"float": 340806},
            "statistics.orbitRadius": {"float": 340806},
            "statistics.pressure": {"float": 340806},
            "statistics.rotationRate": {"float": 340806},
            "statistics.spectralClass": {"str": 340806},
            "statistics.surfaceGravity": {"float": 340806},
            "statistics.temperature": {"float": 340806},
            "typeID": {"int": 342170},
            "uniqueName": {"dict": 137},
            "uniqueName.de": {"str": 137},
            "uniqueName.en": {"str": 137},
            "uniqueName.es": {"str": 137},
            "uniqueName.fr": {"str": 137},
            "uniqueName.ja": {"str": 137},
            "uniqueName.ko": {"str": 137},
            "uniqueName.ru": {"str": 137},
            "uniqueName.zh": {"str": 137},
        },
        "source_info": "mapMoons.jsonl (build 3201939)",
    },
    "mapPlanets.jsonl": {
        "dict_count": 67961,
        "key_info": {
            "_key": {"int": 67961},
            "asteroidBeltIDs": {"list": 17277},
            "attributes": {"dict": 67961},
            "attributes.heightMap1": {"int": 67961},
            "attributes.heightMap2": {"int": 67961},
            "attributes.population": {"bool": 67961},
            "attributes.shaderPreset": {"int": 67961},
            "celestialIndex": {"int": 67961},
            "moonIDs": {"list": 51460},
            "npcStationIDs": {"list": 1098},
            "orbitID": {"int": 67961},
            "position": {"dict": 67961},
            "position.x": {"float": 67961},
            "position.y": {"float": 67961},
            "position.z": {"float": 67961},
            "radius": {"int": 67961},
            "solarSystemID": {"int": 67961},
            "statistics": {"dict": 67961},
            "statistics.density": {"float": 67961},
            "statistics.eccentricity": {"float": 67961},
            "statistics.escapeVelocity": {"float": 67961},
            "statistics.locked": {"bool": 67961},
            "statistics.massDust": {"float": 67961},
            "statistics.massGas": {"float": 67577},
            "statistics.orbitPeriod": {"float": 67577},
            "statistics.orbitRadius": {"float": 67577},
            "statistics.pressure": {"float": 67961},
            "statistics.rotationRate": {"float": 67961},
            "statistics.spectralClass": {"str": 67961},
            "statistics.surfaceGravity": {"float": 67912},
            "statistics.temperature": {"float": 67961},
            "typeID": {"int": 67961},
            "uniqueName": {"dict": 43},
            "uniqueName.de": {"str": 43},
            "uniqueName.en": {"str": 43},
            "uniqueName.es": {"str": 43},
            "uniqueName.fr": {"str": 43},
            "uniqueName.ja": {"str": 43},
            "uniqueName.ko": {"str": 43},
            "uniqueName.ru": {"str": 43},
            "uniqueName.zh": {"str": 43},
        },
        "source_info": "mapPlanets.jsonl (build 3201939)",
    },
    "mapRegions.jsonl": {
        "dict_count": 113,
        "key_info": {
            "_key": {"int": 113},
            "constellationIDs": {"list": 113},
            "description": {"dict": 69},
            "description.de": {"str": 69},
            "description.en": {"str": 69},
            "description.es": {"str": 69},
            "description.fr": {"str": 69},
            "description.ja": {"str": 69},
            "description.ko": {"str": 69},
            "description.ru": {"str": 69},
            "description.zh": {"str": 69},
            "factionID": {"int": 32},
            "name": {"dict": 113},
            "name.de": {"str": 113},
            "name.en": {"str": 113},
            "name.es": {"str": 113},
            "name.fr": {"str": 113},
            "name.ja": {"str": 113},
            "name.ko": {"str": 113},
            "name.ru": {"str": 113},
            "name.zh": {"str": 113},
            "nebulaID": {"int": 113},
            "position": {"dict": 113},
            "position.x": {"float": 113},
            "position.y": {"float": 113},
            "position.z": {"float": 113},
            "wormholeClassID": {"int": 109},
        },
        "source_info": "mapRegions.jsonl (build 3201939)",
    },
    "mapSolarSystems.jsonl": {
        "dict_count": 8437,
        "key_info": {
            "_key": {"int": 8437},
            "border": {"bool": 1997},
            "constellationID": {"int": 8437},
            "corridor": {"bool": 1920},
            "disallowedAnchorCategories": {"list": 538},
            "disallowedAnchorGroups": {"list": 26},
            "factionID": {"int": 16},
            "fringe": {"bool": 782},
            "hub": {"bool": 2678},
            "international": {"bool": 108},
            "luminosity": {"float": 5431},
            "name": {"dict": 8437},
            "name.de": {"str": 8437},
            "name.en": {"str": 8437},
            "name.es": {"str": 8437},
            "name.fr": {"str": 8437},
            "name.ja": {"str": 8437},
            "name.ko": {"str": 8437},
            "name.ru": {"str": 8437},
            "name.zh": {"str": 8437},
            "planetIDs": {"list": 8035},
            "position": {"dict": 8437},
            "position.x": {"float": 8437},
            "position.y": {"float": 8437},
            "position.z": {"float": 8437},
            "position2D": {"dict": 5432},
            "position2D.x": {"float": 5432},
            "position2D.y": {"float": 5432},
            "radius": {"float": 8437},
            "regionID": {"int": 8437},
            "regional": {"bool": 537},
            "securityClass": {"str": 5140},
            "securityStatus": {"float": 8437},
            "starID": {"int": 8036},
            "stargateIDs": {"list": 5215},
            "visualEffect": {"str": 129},
            "wormholeClassID": {"int": 692},
        },
        "source_info": "mapSolarSystems.jsonl (build 3201939)",
    },
    "mapStargates.jsonl": {
        "dict_count": 13776,
        "key_info": {
            "_key": {"int": 13776},
            "destination": {"dict": 13776},
            "destination.solarSystemID": {"int": 13776},
            "destination.stargateID": {"int": 13776},
            "position": {"dict": 13776},
            "position.x": {"float": 13776},
            "position.y": {"float": 13776},
            "position.z": {"float": 13776},
            "solarSystemID": {"int": 13776},
            "typeID": {"int": 13776},
        },
        "source_info": "mapStargates.jsonl (build 3201939)",
    },
    "mapStars.jsonl": {
        "dict_count": 8036,
        "key_info": {
            "_key": {"int": 8036},
            "radius": {"int": 8036},
            "solarSystemID": {"int": 8036},
            "statistics": {"dict": 8036},
            "statistics.age": {"float": 8036},
            "statistics.life": {"float": 8036},
            "statistics.luminosity": {"float": 8036},
            "statistics.spectralClass": {"str": 8036},
            "statistics.temperature": {"float": 8036},
            "typeID": {"int": 8036},
        },
        "source_info": "mapStars.jsonl (build 3201939)",
    },
    "marketGroups.jsonl": {
        "dict_count": 2092,
        "key_info": {
            "_key": {"int": 2092},
            "description": {"dict": 1582},
            "description.de": {"str": 1582},
            "description.en": {"str": 1582},
            "description.es": {"str": 1582},
            "description.fr": {"str": 1582},
            "description.ja": {"str": 1582},
            "description.ko": {"str": 1582},
            "description.ru": {"str": 1582},
            "description.zh": {"str": 1582},
            "hasTypes": {"bool": 2092},
            "iconID": {"int": 2062},
            "name": {"dict": 2092},
            "name.de": {"str": 2092},
            "name.en": {"str": 2092},
            "name.es": {"str": 2092},
            "name.fr": {"str": 2092},
            "name.ja": {"str": 2092},
            "name.ko": {"str": 2092},
            "name.ru": {"str": 2092},
            "name.zh": {"str": 2092},
            "parentGroupID": {"int": 2073},
        },
        "source_info": "marketGroups.jsonl (build 3201939)",
    },
    "masteries.jsonl": {
        "dict_count": 468,
        "key_info": {
            "_key": {"int": 468},
            "_value": {"dict": 2340, "list": 468},
            "_value._key": {"int": 2340},
            "_value._value": {"list": 2340},
        },
        "source_info": "masteries.jsonl (build 3201939)",
    },
    "metaGroups.jsonl": {
        "dict_count": 13,
        "key_info": {
            "_key": {"int": 13},
            "color": {"dict": 10},
            "color.b": {"float": 10},
            "color.g": {"float": 10},
            "color.r": {"float": 10},
            "description": {"dict": 3},
            "description.de": {"str": 3},
            "description.en": {"str": 3},
            "description.es": {"str": 3},
            "description.fr": {"str": 3},
            "description.ja": {"str": 3},
            "description.ko": {"str": 3},
            "description.ru": {"str": 3},
            "description.zh": {"str": 3},
            "iconID": {"int": 12},
            "iconSuffix": {"str": 12},
            "name": {"dict": 13},
            "name.de": {"str": 13},
            "name.en": {"str": 13},
            "name.es": {"str": 13},
            "name.fr": {"str": 13},
            "name.ja": {"str": 13},
            "name.ko": {"str": 13},
            "name.ru": {"str": 13},
            "name.zh": {"str": 13},
        },
        "source_info": "metaGroups.jsonl (build 3201939)",
    },
    "npcCharacters.jsonl": {
        "dict_count": 11303,
        "key_info": {
            "_key": {"int": 11303},
            "agent": {"dict": 10879},
            "agent.agentTypeID": {"int": 10879},
            "agent.divisionID": {"int": 10879},
            "agent.isLocator": {"bool": 10879},
            "agent.level": {"int": 10879},
            "ancestryID": {"int": 11101},
            "bloodlineID": {"int": 11303},
            "careerID": {"int": 11098},
            "ceo": {"bool": 11303},
            "corporationID": {"int": 11303},
            "description": {"str": 24},
            "gender": {"bool": 11303},
            "locationID": {"int": 11257},
            "name": {"dict": 11303},
            "name.de": {"str": 11303},
            "name.en": {"str": 11303},
            "name.es": {"str": 11303},
            "name.fr": {"str": 11303},
            "name.ja": {"str": 11303},
            "name.ko": {"str": 11303},
            "name.ru": {"str": 11303},
            "name.zh": {"str": 11303},
            "raceID": {"int": 11303},
            "schoolID": {"int": 11095},
            "skills": {"dict": 1145, "list": 421},
            "skills.typeID": {"int": 1145},
            "specialityID": {"int": 11096},
            "startDate": {"str": 11186},
            "uniqueName": {"bool": 11303},
        },
        "source_info": "npcCharacters.jsonl (build 3201939)",
    },
    "npcCorporationDivisions.jsonl": {
        "dict_count": 10,
        "key_info": {
            "_key": {"int": 10},
            "description": {"dict": 5},
            "description.de": {"str": 5},
            "description.en": {"str": 5},
            "description.es": {"str": 5},
            "description.fr": {"str": 5},
            "description.ja": {"str": 5},
            "description.ko": {"str": 5},
            "description.ru": {"str": 5},
            "description.zh": {"str": 5},
            "displayName": {"str": 9},
            "internalName": {"str": 10},
            "leaderTypeName": {"dict": 10},
            "leaderTypeName.de": {"str": 10},
            "leaderTypeName.en": {"str": 10},
            "leaderTypeName.es": {"str": 10},
            "leaderTypeName.fr": {"str": 10},
            "leaderTypeName.ja": {"str": 10},
            "leaderTypeName.ko": {"str": 10},
            "leaderTypeName.ru": {"str": 10},
            "leaderTypeName.zh": {"str": 10},
            "name": {"dict": 10},
            "name.de": {"str": 10},
            "name.en": {"str": 10},
            "name.es": {"str": 10},
            "name.fr": {"str": 10},
            "name.ja": {"str": 10},
            "name.ko": {"str": 10},
            "name.ru": {"str": 10},
            "name.zh": {"str": 10},
        },
        "source_info": "npcCorporationDivisions.jsonl (build 3201939)",
    },
    "npcCorporations.jsonl": {
        "dict_count": 283,
        "key_info": {
            "_key": {"int": 283},
            "allowedMemberRaces": {"list": 212},
            "ceoID": {"int": 260},
            "corporationTrades": {"dict": 17791, "list": 184},
            "corporationTrades._key": {"int": 17791},
            "corporationTrades._value": {"float": 17791},
            "deleted": {"bool": 283},
            "description": {"dict": 280},
            "description.de": {"str": 279},
            "description.en": {"str": 280},
            "description.es": {"str": 280},
            "description.fr": {"str": 280},
            "description.ja": {"str": 280},
            "description.ko": {"str": 280},
            "description.ru": {"str": 279},
            "description.zh": {"str": 280},
            "divisions": {"dict": 247, "list": 114},
            "divisions._key": {"int": 247},
            "divisions.divisionNumber": {"int": 247},
            "divisions.leaderID": {"int": 247},
            "divisions.size": {"int": 247},
            "enemyID": {"int": 250},
            "exchangeRates": {"dict": 146, "list": 1},
            "exchangeRates._key": {"int": 146},
            "exchangeRates._value": {"float": 146},
            "extent": {"str": 283},
            "factionID": {"int": 273},
            "friendID": {"int": 246},
            "hasPlayerPersonnelManager": {"bool": 283},
            "iconID": {"int": 252},
            "initialPrice": {"int": 283},
            "investors": {"dict": 406, "list": 227},
            "investors._key": {"int": 406},
            "investors._value": {"int": 406},
            "lpOfferTables": {"list": 181},
            "mainActivityID": {"int": 266},
            "memberLimit": {"int": 283},
            "minSecurity": {"float": 283},
            "minimumJoinStanding": {"int": 283},
            "name": {"dict": 283},
            "name.de": {"str": 283},
            "name.en": {"str": 283},
            "name.es": {"str": 283},
            "name.fr": {"str": 283},
            "name.ja": {"str": 283},
            "name.ko": {"str": 283},
            "name.ru": {"str": 283},
            "name.zh": {"str": 283},
            "raceID": {"int": 257},
            "secondaryActivityID": {"int": 34},
            "sendCharTerminationMessage": {"bool": 283},
            "shares": {"int": 283},
            "size": {"str": 283},
            "sizeFactor": {"float": 189},
            "solarSystemID": {"int": 261},
            "stationID": {"int": 262},
            "taxRate": {"float": 283},
            "tickerName": {"str": 283},
            "uniqueName": {"bool": 283},
        },
        "source_info": "npcCorporations.jsonl (build 3201939)",
    },
    "npcStations.jsonl": {
        "dict_count": 5154,
        "key_info": {
            "_key": {"int": 5154},
            "celestialIndex": {"int": 5153},
            "operationID": {"int": 5154},
            "orbitID": {"int": 5154},
            "orbitIndex": {"int": 3968},
            "ownerID": {"int": 5154},
            "position": {"dict": 5154},
            "position.x": {"float": 5154},
            "position.y": {"float": 5154},
            "position.z": {"float": 5154},
            "reprocessingEfficiency": {"float": 5154},
            "reprocessingHangarFlag": {"int": 5154},
            "reprocessingStationsTake": {"float": 5154},
            "solarSystemID": {"int": 5154},
            "typeID": {"int": 5154},
            "useOperationName": {"bool": 5154},
        },
        "source_info": "npcStations.jsonl (build 3201939)",
    },
    "planetResources.jsonl": {
        "dict_count": 25798,
        "key_info": {
            "_key": {"int": 25798},
            "power": {"int": 12126},
            "reagent": {"dict": 3462},
            "reagent.amount_per_cycle": {"int": 3462},
            "reagent.cycle_period": {"int": 3462},
            "reagent.secured_capacity": {"int": 3462},
            "reagent.type_id": {"int": 3462},
            "reagent.unsecured_capacity": {"int": 3462},
            "workforce": {"int": 10210},
        },
        "source_info": "planetResources.jsonl (build 3201939)",
    },
    "planetSchematics.jsonl": {
        "dict_count": 68,
        "key_info": {
            "_key": {"int": 68},
            "cycleTime": {"int": 68},
            "name": {"dict": 68},
            "name.de": {"str": 68},
            "name.en": {"str": 68},
            "name.es": {"str": 68},
            "name.fr": {"str": 68},
            "name.ja": {"str": 68},
            "name.ko": {"str": 68},
            "name.ru": {"str": 68},
            "name.zh": {"str": 68},
            "pins": {"list": 68},
            "types": {"dict": 203, "list": 68},
            "types._key": {"int": 203},
            "types.isInput": {"bool": 203},
            "types.quantity": {"int": 203},
        },
        "source_info": "planetSchematics.jsonl (build 3201939)",
    },
    "races.jsonl": {
        "dict_count": 11,
        "key_info": {
            "_key": {"int": 11},
            "description": {"dict": 8},
            "description.de": {"str": 8},
            "description.en": {"str": 8},
            "description.es": {"str": 8},
            "description.fr": {"str": 8},
            "description.ja": {"str": 8},
            "description.ko": {"str": 8},
            "description.ru": {"str": 8},
            "description.zh": {"str": 8},
            "iconID": {"int": 5},
            "name": {"dict": 11},
            "name.de": {"str": 11},
            "name.en": {"str": 11},
            "name.es": {"str": 11},
            "name.fr": {"str": 11},
            "name.ja": {"str": 11},
            "name.ko": {"str": 11},
            "name.ru": {"str": 11},
            "name.zh": {"str": 11},
            "shipTypeID": {"int": 4},
            "skills": {"dict": 200, "list": 4},
            "skills._key": {"int": 200},
            "skills._value": {"int": 200},
        },
        "source_info": "races.jsonl (build 3201939)",
    },
    "skinLicenses.jsonl": {
        "dict_count": 11624,
        "key_info": {
            "_key": {"int": 11624},
            "duration": {"int": 11624},
            "isSingleUse": {"bool": 4342},
            "licenseTypeID": {"int": 11624},
            "skinID": {"int": 11624},
        },
        "source_info": "skinLicenses.jsonl (build 3201939)",
    },
    "skinMaterials.jsonl": {
        "dict_count": 837,
        "key_info": {
            "_key": {"int": 837},
            "displayName": {"dict": 835},
            "displayName.de": {"str": 835},
            "displayName.en": {"str": 835},
            "displayName.es": {"str": 835},
            "displayName.fr": {"str": 835},
            "displayName.ja": {"str": 835},
            "displayName.ko": {"str": 835},
            "displayName.ru": {"str": 835},
            "displayName.zh": {"str": 835},
            "materialSetID": {"int": 837},
        },
        "source_info": "skinMaterials.jsonl (build 3201939)",
    },
    "skins.jsonl": {
        "dict_count": 6795,
        "key_info": {
            "_key": {"int": 6795},
            "allowCCPDevs": {"bool": 6795},
            "internalName": {"str": 6795},
            "isStructureSkin": {"bool": 941},
            "skinDescription": {"dict": 2474},
            "skinDescription.de": {"str": 2473},
            "skinDescription.en": {"str": 2474},
            "skinDescription.es": {"str": 2474},
            "skinDescription.fr": {"str": 2474},
            "skinDescription.ja": {"str": 2474},
            "skinDescription.ko": {"str": 2474},
            "skinDescription.ru": {"str": 2474},
            "skinDescription.zh": {"str": 2474},
            "skinMaterialID": {"int": 6795},
            "types": {"list": 6795},
            "visibleSerenity": {"bool": 6795},
            "visibleTranquility": {"bool": 6795},
        },
        "source_info": "skins.jsonl (build 3201939)",
    },
    "sovereigntyUpgrades.jsonl": {
        "dict_count": 49,
        "key_info": {
            "_key": {"int": 49},
            "fuel": {"dict": 14},
            "fuel.hourly_upkeep": {"int": 14},
            "fuel.startup_cost": {"int": 14},
            "fuel.type_id": {"int": 14},
            "mutually_exclusive_group": {"str": 49},
            "power_allocation": {"int": 44},
            "power_production": {"int": 4},
            "workforce_allocation": {"int": 44},
            "workforce_production": {"int": 4},
        },
        "source_info": "sovereigntyUpgrades.jsonl (build 3201939)",
    },
    "stationOperations.jsonl": {
        "dict_count": 66,
        "key_info": {
            "_key": {"int": 66},
            "activityID": {"int": 66},
            "border": {"float": 66},
            "corridor": {"float": 66},
            "description": {"dict": 54},
            "description.de": {"str": 54},
            "description.en": {"str": 54},
            "description.es": {"str": 54},
            "description.fr": {"str": 54},
            "description.ja": {"str": 54},
            "description.ko": {"str": 54},
            "description.ru": {"str": 54},
            "description.zh": {"str": 54},
            "fringe": {"float": 66},
            "hub": {"float": 66},
            "manufacturingFactor": {"float": 66},
            "operationName": {"dict": 66},
            "operationName.de": {"str": 66},
            "operationName.en": {"str": 66},
            "operationName.es": {"str": 66},
            "operationName.fr": {"str": 66},
            "operationName.ja": {"str": 66},
            "operationName.ko": {"str": 66},
            "operationName.ru": {"str": 66},
            "operationName.zh": {"str": 66},
            "ratio": {"float": 66},
            "researchFactor": {"float": 66},
            "services": {"list": 66},
            "stationTypes": {"dict": 224, "list": 47},
            "stationTypes._key": {"int": 224},
            "stationTypes._value": {"int": 224},
        },
        "source_info": "stationOperations.jsonl (build 3201939)",
    },
    "stationServices.jsonl": {
        "dict_count": 27,
        "key_info": {
            "_key": {"int": 27},
            "description": {"dict": 1},
            "description.de": {"str": 1},
            "description.en": {"str": 1},
            "description.es": {"str": 1},
            "description.fr": {"str": 1},
            "description.ja": {"str": 1},
            "description.ko": {"str": 1},
            "description.ru": {"str": 1},
            "description.zh": {"str": 1},
            "serviceName": {"dict": 27},
            "serviceName.de": {"str": 27},
            "serviceName.en": {"str": 27},
            "serviceName.es": {"str": 27},
            "serviceName.fr": {"str": 27},
            "serviceName.ja": {"str": 27},
            "serviceName.ko": {"str": 27},
            "serviceName.ru": {"str": 27},
            "serviceName.zh": {"str": 27},
        },
        "source_info": "stationServices.jsonl (build 3201939)",
    },
    "translationLanguages.jsonl": {
        "dict_count": 8,
        "key_info": {"_key": {"str": 8}, "name": {"str": 8}},
        "source_info": "translationLanguages.jsonl (build 3201939)",
    },
    "typeBonus.jsonl": {
        "dict_count": 641,
        "key_info": {
            "_key": {"int": 641},
            "iconID": {"int": 66},
            "miscBonuses": {"dict": 369, "list": 76},
            "miscBonuses.bonus": {"float": 313, "int": 8},
            "miscBonuses.bonusText": {"dict": 369},
            "miscBonuses.bonusText.de": {"str": 369},
            "miscBonuses.bonusText.en": {"str": 369},
            "miscBonuses.bonusText.es": {"str": 369},
            "miscBonuses.bonusText.fr": {"str": 369},
            "miscBonuses.bonusText.ja": {"str": 369},
            "miscBonuses.bonusText.ko": {"str": 369},
            "miscBonuses.bonusText.ru": {"str": 369},
            "miscBonuses.bonusText.zh": {"str": 369},
            "miscBonuses.importance": {"int": 369},
            "miscBonuses.isPositive": {"bool": 272},
            "miscBonuses.unitID": {"int": 321},
            "roleBonuses": {"dict": 1823, "list": 477},
            "roleBonuses.bonus": {"float": 864, "int": 277},
            "roleBonuses.bonusText": {"dict": 1823},
            "roleBonuses.bonusText.de": {"str": 1822},
            "roleBonuses.bonusText.en": {"str": 1823},
            "roleBonuses.bonusText.es": {"str": 1821},
            "roleBonuses.bonusText.fr": {"str": 1822},
            "roleBonuses.bonusText.ja": {"str": 1822},
            "roleBonuses.bonusText.ko": {"str": 1822},
            "roleBonuses.bonusText.ru": {"str": 1822},
            "roleBonuses.bonusText.zh": {"str": 1822},
            "roleBonuses.importance": {"int": 1823},
            "roleBonuses.unitID": {"int": 1142},
            "types": {"dict": 773, "list": 525},
            "types._key": {"int": 773},
            "types._value": {"dict": 1633, "list": 773},
            "types._value.bonus": {"float": 1081, "int": 535},
            "types._value.bonusText": {"dict": 1633},
            "types._value.bonusText.de": {"str": 1633},
            "types._value.bonusText.en": {"str": 1633},
            "types._value.bonusText.es": {"str": 1633},
            "types._value.bonusText.fr": {"str": 1633},
            "types._value.bonusText.ja": {"str": 1633},
            "types._value.bonusText.ko": {"str": 1633},
            "types._value.bonusText.ru": {"str": 1633},
            "types._value.bonusText.zh": {"str": 1633},
            "types._value.importance": {"int": 1633},
            "types._value.unitID": {"int": 1616},
        },
        "source_info": "typeBonus.jsonl (build 3201939)",
    },
    "typeDogma.jsonl": {
        "dict_count": 26007,
        "key_info": {
            "_key": {"int": 26007},
            "dogmaAttributes": {"dict": 620703, "list": 26007},
            "dogmaAttributes.attributeID": {"int": 620703},
            "dogmaAttributes.value": {"float": 620703},
            "dogmaEffects": {"dict": 52356, "list": 15522},
            "dogmaEffects.effectID": {"int": 52356},
            "dogmaEffects.isDefault": {"bool": 52356},
        },
        "source_info": "typeDogma.jsonl (build 3201939)",
    },
    "typeMaterials.jsonl": {
        "dict_count": 9485,
        "key_info": {
            "_key": {"int": 9485},
            "materials": {"dict": 46664, "list": 9475},
            "materials.materialTypeID": {"int": 46664},
            "materials.quantity": {"int": 46664},
            "randomizedMaterials": {"dict": 24, "list": 10},
            "randomizedMaterials.materialTypeID": {"int": 24},
            "randomizedMaterials.quantityMax": {"int": 24},
            "randomizedMaterials.quantityMin": {"int": 24},
        },
        "source_info": "typeMaterials.jsonl (build 3201939)",
    },
    "types.jsonl": {
        "dict_count": 51135,
        "key_info": {
            "_key": {"int": 51135},
            "basePrice": {"float": 13854},
            "capacity": {"float": 9544},
            "description": {"dict": 33161},
            "description.de": {"str": 33156},
            "description.en": {"str": 33161},
            "description.es": {"str": 33157},
            "description.fr": {"str": 33157},
            "description.ja": {"str": 33157},
            "description.ko": {"str": 33157},
            "description.ru": {"str": 33157},
            "description.zh": {"str": 33156},
            "factionID": {"int": 1337},
            "graphicID": {"int": 17711},
            "groupID": {"int": 51135},
            "iconID": {"int": 22255},
            "marketGroupID": {"int": 19118},
            "mass": {"float": 20539},
            "metaGroupID": {"int": 13377},
            "name": {"dict": 51135},
            "name.de": {"str": 51122},
            "name.en": {"str": 51135},
            "name.es": {"str": 51123},
            "name.fr": {"str": 51123},
            "name.ja": {"str": 51123},
            "name.ko": {"str": 51124},
            "name.ru": {"str": 51123},
            "name.zh": {"str": 51124},
            "portionSize": {"int": 51135},
            "published": {"bool": 51135},
            "raceID": {"int": 22660},
            "radius": {"float": 15016},
            "soundID": {"int": 5008},
            "variationParentTypeID": {"int": 4751},
            "volume": {"float": 45611},
        },
        "source_info": "types.jsonl (build 3201939)",
    },
}
